import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar is fixed, add padding-top to main content */}
        <Navbar />
        
        <main className="min-h-screen pt-16 md:pt-20"> {/* Adjust padding-top based on navbar height */}
          <div className="flex flex-col items-center justify-center min-h-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}